version: '3'
services:
    mongo:
        restart: always
        build:
            context: ./mongo-db
            dockerfile: Dockerfile
        ports:
            - 27017:27017
    api:
        depends_on:
            - mongo
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - 3001:3001
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - NODE_PORT=3001
    keycloak:
        build:
            context: keycloak
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
          - ./keycloak:/tmp/todo-list/
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=password
